#file: noinspection YAMLSchemaValidation
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
#    volumes:
#      - ./backend:/app
#      - type: bind
#        source: /mnt/backup/unix-lab.db
#        target: /etc/unix-lab/unix-lab.db

    frontend:
      build:
        dockerfile: Dockerfile
        context: ./frontend
      ports:
        - 3000:3000

volumes:
  db-postgres: