name: Deploying to staging servers
on:
  push:
    branches:
      - master

env:
  PROD_PATH: .
  ENV_PATH: .env
  COMPOSE_FILE: docker-compose.prod.yml
  START_SCRIPT: bin/deploy.start.sh
  IMAGE_NAME:  ${{ github.event.repository.name || 'attendance-test' }}

jobs:
  prepare-image:
    runs-on: ubuntu-latest
    outputs:
      prod_hosts: ${{ steps.generate-hosts.outputs.hosts }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/generate-hosts
        id: generate-hosts
        with:
          config_file: "./.github/data/staging.json"


  deploy:
    runs-on: ubuntu-latest
    needs: [prepare-image]
    strategy:
      matrix:
        server: ${{ fromJson(needs.prepare-image.outputs.prod_hosts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

    environment:
      name: ${{ matrix.server.hostname }}
